apiVersion: v1
data:
  config: "{\n\"_id\": \"rs0\",\n\"version\": 1,\n\"members\":\n  [\n    {\"_id\":
    0, \"host\": \"mongo-0:27017\"},\n    {\"_id\": 1, \"host\": \"mongo-1:27017\"},\n
    \   {\"_id\": 2, \"host\": \"mongo-2:27017\"},\n  ]                                    \n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-config
